#!/usr/bin/python

# 
# Copyright (c) 2016, Shilin Victor <chrono.monochrome@gmail.com>
# 
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# General Public License for more details.
#
# 

import sys, os

DEBUG = 1
VERBOSE_DEBUG = 0	
KERNEL="./%s" % sys.argv[1]
SCRIPT="./%s" % sys.argv[2]
CMDLINE="./%s" % sys.argv[3]
DIR = "".join(KERNEL.split("/")[:-1]) + "/"

def debug_print(s, verbose_debug_flag = 1):
	if DEBUG and verbose_debug_flag:
		os.system('echo %s'%s)


def gen_cmdline_script(kernel):
	zimage = open(kernel, "rb").read()
	start = zimage.find("androidboot")
	if start <= 0: return -1
	end = zimage.find("\x00", start)
	sz = end - start
	if ((end <= 0) or (sz > 2048)) : return -1

	script = """#!/sbin/sh
# this file is automatically generated by the build system, don't edit

set -x

if [  "$(stat /ramdisk/cmdline.txt | grep -c %d)" != "1" ] || ! test -f /ramdisk/cmdline.txt; then
	if ! test -f /tmp/cmdline.txt ; then
		exit
	fi

	cp /tmp/cmdline.txt /ramdisk/cmdline.txt
fi

if test -f /ramdisk/.dont_use_ramdisk_cmdline ; then
	exit
fi

printf %%%ds > /tmp/new_cmdline.txt
dd conv=notrunc if=/ramdisk/cmdline.txt of=/tmp/new_cmdline.txt bs=%d count=1
dd conv=notrunc if=/tmp/new_cmdline.txt of=%s bs=1 seek=%d
""" 	% (sz -1, sz - 1, sz - 1, "$1", start)

	open(SCRIPT, "wb").write(script)
	open(CMDLINE, "wb").write(zimage[start : end -1])

gen_cmdline_script(KERNEL)
